// understanding Exception handling
#include<iostream>
using namespace std;
int main(){
	int x=5,y=0;
	cout<<x/y;
	return 0;
}
